### ISSUE TITLE
find_trigger_files() fetches a larger window than specified for small windows of time.

### ISSUE THREAD

**Issue by rutujagurav** [gwpy/gwtrigfind#29]
Here's an example codeline from O2:
`trigs = gwtrigfind.find_trigger_files('L1:GDS-CALIB_STRAIN', 'omicron', 1165071610.81, 1165071612.94)`

This code line returns a file ('file:///home/detchar/triggers/L1/GDS_CALIB_STRAIN_OMICRON/11650/L1-GDS_CALIB_STRAIN_OMICRON-1165068670-2950.xml.gz') for triggers in a wider window (1165068670.25 - 1165071619.98) of ~2950 s than the input window of ~2 s.

Is this normal behavior?

**Comment by duncanmmacleod** [comment]
Hi @rutujagurav, yes, this is expected. The function returns the _file path_ that fulfils the interval, not the triggers. Your interval is short, but is contained wholly inside a much larger file, so that is what gets returned. There are no shorter files that cover the same interval (typically only one file covers a given GPS time).

**Comment by rutujagurav** [comment]
Thank you for that clarification. Is the file size fixed across all channels in terms of the length of time it contains?

**Comment by duncanmmacleod** [comment]
No, the files are unpredictable lengths across time segments and across channels due to the way data are processed.

**Comment by rutujagurav** [comment]
Thank you for the clarification, @duncanmmacleod.
