### ISSUE TITLE
gwtrigfind.find_trigger_files() not finding a directory VERSUS returning no files VERSUS returned file is empty.

### ISSUE THREAD

**Issue by rutujagurav** [gwpy/gwtrigfind#30]
Hello,
I apologize for this quite pedestrian question.

I have encountered 3 different possibilities when using find_trigger_files().
1) If it can't find an omicron directory for a channel for a given time window, it throws ValueError: No channel-level directory found, inappropriate ETG...
2) If it finds a directory, sometimes there are no files in that directory.
3) If it finds a directory and also some file(s) in that directory, the file(s) is(are) empty.

What's the difference between these 3 scenarios?
Do all these scenarios mean **there were no triggers** above SNR 5.0 during my time window in that channel? 
Or do any of these scenarios mean **triggers were not collected** for my time window from that channel for a variety of reasons (detector lockloss, ETG computational cost too high, known problem with the sensor corresponding to the channel)?

**Comment by duncanmmacleod** [comment]
> * If it can't find an omicron directory for a channel for a given time window, it throws ValueError: No channel-level directory found, inappropriate ETG...

This means that the channel you are looking for has not been processed (ever?) using Omicron

> * If it finds a directory, sometimes there are no files in that directory.

This means that the time period you are looking for was not covered during standard processing. This can either be because the interferometer wasn't in the right state at that time (i.e not locked) or there was an error during processing and the data were never re-processed.

> * If it finds a directory and also some file(s) in that directory, the file(s) is(are) empty.

This means that the data were processed, but Omicron didn't detect any noise excesses above the SNR threshold during that period. This may be for a number of reasons, anything from 'the channel was just very quiet during that period' to 'the channel is broken and is constantly recording static'.

**Comment by duncanmmacleod** [comment]
Apologies for the late response, so late as probably be useless, but having an answer here for the record might come in handy for people googling the same question.
